"""init: projects, campaign_files, trees, observations

Revision ID: a8888efd3ae8
Revises: 
Create Date: 2026-09-14 17:39:44.204983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8888efd3ae8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('locality', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mapping_version', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trees', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sha256', name='uq_campaign_project_file')
    )
    op.create_index(op.f('ix_campaign_files_project_id'), 'campaign_files', ['project_id'], unique=False)
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.String(length=200), nullable=False),
    sa.Column('species', sa.String(length=300), nullable=False),
    sa.Column('family', sa.String(length=200), nullable=True),
    sa.Column('common_name', sa.String(length=300), nullable=True),
    sa.Column('guild', sa.String(length=100), nullable=True),
    sa.Column('plot_id', sa.String(length=100), nullable=True),
    sa.Column('locality', sa.String(length=200), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tree_id', name='uq_tree_project_tree_id')
    )
    op.create_index(op.f('ix_trees_project_id'), 'trees', ['project_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_row_id', sa.Integer(), nullable=False),
    sa.Column('campaign', sa.Integer(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('crown_diameter_m', sa.Float(), nullable=True),
    sa.Column('dap_cm', sa.Float(), nullable=True),
    sa.Column('dap_status', sa.String(length=20), nullable=False),
    sa.Column('phytosanitary', sa.String(length=50), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('colonization', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tree_row_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tree_row_id', 'campaign', name='uq_observation_tree_campaign')
    )
    op.create_index(op.f('ix_observations_tree_row_id'), 'observations', ['tree_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_tree_row_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_trees_project_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_campaign_files_project_id'), table_name='campaign_files')
    op.drop_table('campaign_files')
    op.drop_table('projects')
    # ### end Alembic commands ###
